COMMENT


Mod file auto-generated by pyramidal on 2012-08-29 13:05:53.353871


ENDCOMMENT


NEURON {
    SUFFIX k_slow
    USEION k READ ek WRITE ik
    RANGE gbar
    RANGE gk
    RANGE m
    GLOBAL m_A_A,m_A_B,m_A_C,m_A_D,m_A_F
    GLOBAL m_B_A,m_B_B,m_B_C,m_B_D,m_B_F
    RANGE minf, mtau
    GLOBAL k_reversal_potential
    GLOBAL vmin, vmax
}




PARAMETER {
    m_A_A    = 2.5    (mV)
    m_A_B    = -0.1    (ms)
    m_A_C    = -1.0    (mV)
    m_A_D    = -25.0    (mV)
    m_A_F    = -10.0    (mV)
    m_B_A    = 4.0    (mV)
    m_B_B    = 0.0    (mV)
    m_B_C    = 0.0        
    m_B_D    = 0.0    (mV)
    m_B_F    = 18.0    (mV)
    gbar     = 3600.0      (pS/um2)
    k_reversal_potential = -12.0    (mV)
    v                                 (mV)
    dt                                (ms)
    vmin     = -30    (mV)
    vmax     = 120    (mV)
}




UNITS {
     (mA) = (milliamp)
     (mV) = (millivolt)
     (pS) = (picosiemens)
     (um) = (micron)
}




ASSIGNED {
    ik    (mA/cm2)
    gk    (pS/um2)
    ek    (mV)
    minf
    mtau (ms)
}




STATE { m }




INITIAL {
    trates(v)
    m = minf
}




BREAKPOINT {
    SOLVE states METHOD cnexp
    gk = gbar*m*m*m*m
    ik = (1e-4) * gk * (v - k_reversal_potential)
}




LOCAL mexp




DERIVATIVE states {
    trates(v)
    m' =  (minf-m)/mtau
}




PROCEDURE trates(v) {
    TABLE minf, mtau
    FROM vmin TO vmax WITH 199
    rates(v): not consistently executed from here if usetable == 1
}




PROCEDURE rates(vm) {
    LOCAL  a, b
    a = trap0(vm,m_A_A,m_A_B,m_A_C,m_A_D,m_A_F)
    b = trap0(vm,m_B_A,m_B_B,m_B_C,m_B_D,m_B_F)
    mtau = 1/(a+b)
    minf = a/(a+b)
}




FUNCTION trap0(v,A,B,C,D,F) {
	if (fabs(v/A) > 1e-6) {
	        trap0 = (A + B * v) / (C + exp((v + D)/F))
	} else {
	        trap0 = B * F
 	}
}


